### ISSUE TITLE
Why not compare with ESRGAN

### ISSUE THREAD

**Issue by qingfengmingyue** [SHI-Labs/Cross-Scale-Non-Local-Attention#2]
Why not compare with ESRGAN?

**Comment by HarukiYqM** [comment]
ESRGAN focuses on perceptual-oriented super resolution but our work focuses on PSNR oriented SR. Although they provided a PSNR oriented model, but the training set is significantly different than us (DF2K (I.e DIV2K+Flickr2K)VS only DIV2K), which makes comparison unfair. Instead of follow their training setting, this paper follows more common practice used in SAN, RCAN, OISR etc..
