### ISSUE TITLE
When I test RCAN and SAN using your code, All results much more better.

### ISSUE THREAD

**Issue by Senwang98** [SHI-Labs/Cross-Scale-Non-Local-Attention#24]
When I test RCAN and SAN using your code, All results much more better.
So I think your codes have bug, and the results for paper should be wrong.

**Comment by HarukiYqM** [comment]
> When I test RCAN and SAN using your code, All results much more better.
> So I think your codes have bug, and the results for paper should be wrong.

I did not observe this effects after carefully testing these models with this code today. Please note the entire training and inference part of this code is fully based on EDSR 1.1 (https://github.com/thstkdgus35/EDSR-PyTorch) version with no modification.

**Comment by Ralapfranco** [comment]
My EDSR training is also much better than csnln. My csnln training epoch was only set 90 times, because I found that he converged early.

**Comment by HarukiYqM** [comment]
> My EDSR training is also much better than csnln. My csnln training epoch was only set 90 times, because I found that he converged early.

Please do try train more epochs as stated in the paper If you want to reproduce the results. If you have tried to train other complex models, you will see EDSR always converges faster than almost any of them at early epochs, mainly because its simple structure is easier to optimize. Complex models will out perform the edsr around 200-300 epochs.
